package com.amsdams.demoreviewservice;

import java.util.ArrayList;
import java.util.List;

import org.springframework.data.mongodb.core.mapping.Document;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Document(collection = "Reviews")
@AllArgsConstructor
@NoArgsConstructor
public class Review {
	public Review(Integer productId) {
		this.productId = productId;
	}

	public Review(String reviewId, int productId, int version) {
		this.id = reviewId;
		this.productId = productId;
		this.version = version;
		
	}

	public Review(int productId, int version) {
		this.productId = productId;
		this.version = version;
	}

	/**
	 * The ID, or primary key, of the Review, as generated by MongoDB.
	 */
	private String id;

	/**
	 * The product ID for which this review is applicable.
	 */
	private Integer productId;

	/**
	 * The version of the review, which is an increasing number starting with 1.
	 */
	private Integer version = 1;

	/**
	 * A list of review entries - these contain user reviews of the product.
	 */
	private List<ReviewEntry> entries = new ArrayList<>();
}
